# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 10:08
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('p_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text_min',
            field=tinymce.models.HTMLField(blank=True, max_length=600, null=True, verbose_name='\u0410\u043d\u043d\u043e\u0442\u0430\u0446\u0438\u044f \u043a \u0441\u0442\u0430\u0442\u044c\u0435'),
        ),
    ]
